FROM ubuntu:22.04


# Installing Chrome Headless
RUN apt update
RUN apt install -y libappindicator1 fonts-liberation curl
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome*.deb

# Installing NodeJs
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN nvm install 16.17

# Installing Angular
RUN npm install -g @angular/cli
RUN ng config -g cli.packageManager yarn
